# python classification_sGAN.py -r /home/maelle/Documents/Stage_m2/Results/resultats_classification/sGAN/DIC --data DIC -c                                                                                                                                                                                                               
# python classification_sGAN.py -r /home/maelle/Documents/Stage_m2/Results/resultats_classification/sGAN/DIC --data DIC -m TL -c                                                                                                                                                                                                                
# python classification_sGAN.py -r /home/maelle/Documents/Stage_m2/Results/resultats_classification/sGAN/DIC --data DIC -m FR -c                           

# python classification_wGAN.py -r /home/maelle/Documents/Stage_m2/Results/resultats_classification/wGAN/DIC --data DIC -c                                                                                                                                                                                                              
# python classification_wGAN.py -r /home/maelle/Documents/Stage_m2/Results/resultats_classification/wGAN/DIC --data DIC -m TL -c                                                                                                                                                                                                             
# python classification_wGAN.py -r /home/maelle/Documents/Stage_m2/Results/resultats_classification/wGAN/DIC --data DIC -m FR -c                                                                                                                                                                                            


python classification_sGAN.py -r /home/maelle/Documents/Stage_m2/Results/classif_dna/sGAN --data Nagao -c                                                                                                                                                                                                               
python classification_sGAN.py -r /home/maelle/Documents/Stage_m2/Results/classif_dna/sGAN --data Nagao -m TL -c                                                                                                                                                                                                                
python classification_sGAN.py -r /home/maelle/Documents/Stage_m2/Results/classif_dna/sGAN --data Nagao -m FR -c                           

python classification_wGAN.py -r /home/maelle/Documents/Stage_m2/Results/classif_dna/wGAN --data Nagao -c                                                                                                                                                                                                              
python classification_wGAN.py -r /home/maelle/Documents/Stage_m2/Results/classif_dna/wGAN --data Nagao -m TL -c                                                                                                                                                                                                             
python classification_wGAN.py -r /home/maelle/Documents/Stage_m2/Results/classif_dna/wGAN --data Nagao -m FR -c      